{% set name = "hugo-extended" %}
{% set version = "0.105.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://github.com/gohugoio/hugo/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 3e0ced73b0acc1c8ae13fe118c7f4ba292a43f73e60a5b1d2f8301c574dc1596
  url: https://github.com/gohugoio/hugo/releases/download/v{{ version }}/hugo_extended_{{ version }}_Linux-64bit.tar.gz

build:
  number: 0
  skip: True  # [not linux]

test:
  commands:
    - hugo version

about:
  summary: A Fast and Flexible Static Site Generator built with love by bep, spf13 and friends in Go.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  home: https://gohugo.io
  doc_url: https://github.com/gohugoio/hugo
  dev_url: https://github.com/gohugoio/hugo

extra:
  recipe-maintainers:
    - xmnlab
    - EverVino
